// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMto48VT_FvREOfKWoe2KlmfrOaA0rxsU',
    appId: '1:230636813956:web:d914573cb6f51c9c4accd1',
    messagingSenderId: '230636813956',
    projectId: 'uber-376d4',
    authDomain: 'uber-376d4.firebaseapp.com',
    storageBucket: 'uber-376d4.firebasestorage.app',
    measurementId: 'G-R25YYBYQTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6gqE-0VmIbJZdcjQholwARCQdjW8KTM',
    appId: '1:230636813956:android:a549f0c5676f40f04accd1',
    messagingSenderId: '230636813956',
    projectId: 'uber-376d4',
    storageBucket: 'uber-376d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADIwz_6xf4hsBBAh9JoCGAp6CqAEDxVwo',
    appId: '1:230636813956:ios:2961cd734aa20b9e4accd1',
    messagingSenderId: '230636813956',
    projectId: 'uber-376d4',
    storageBucket: 'uber-376d4.firebasestorage.app',
    iosBundleId: 'com.example.uber',
  );
}
